### ISSUE TITLE
[bug] A null error occurs when entering

### ISSUE THREAD

**Issue by jd07159** [bivashy/NanoLimboPlugin#12]
```[09:31:25 ERROR]: java.lang.NullPointerException: Cannot invoke "net.kyori.adventure.text.Component.replaceText(java.util.function.Consumer)" because "component" is null
[09:31:25 ERROR]:       at com.bivashy.limbo.config.MessageConfiguration.message(MessageConfiguration.java:39)
[09:31:25 ERROR]:       at com.bivashy.limbo.command.ConnectionCountCommand.execute(ConnectionCountCommand.java:21)
[09:31:25 ERROR]:       at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[09:31:25 ERROR]:       at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758)
[09:31:25 ERROR]:       at revxrsal.commands.core.reflect.MethodHandlesCallerFactory$1.call(MethodHandlesCallerFactory.java:35)
[09:31:25 ERROR]:       at revxrsal.commands.core.reflect.MethodCaller.lambda$bindTo$0(MethodCaller.java:29)
[09:31:25 ERROR]:       at revxrsal.commands.core.BaseCommandDispatcher.execute(BaseCommandDispatcher.java:88)
[09:31:25 ERROR]:       at revxrsal.commands.core.BaseCommandDispatcher.searchCategory(BaseCommandDispatcher.java:69)
[09:31:25 ERROR]:       at revxrsal.commands.core.BaseCommandDispatcher.eval(BaseCommandDispatcher.java:44)
[09:31:25 ERROR]:       at revxrsal.commands.core.BaseCommandHandler.dispatch(BaseCommandHandler.java:519)
[09:31:25 ERROR]:       at revxrsal.commands.velocity.core.VelocitySimpleCommand.execute(VelocitySimpleCommand.java:27)
[09:31:25 ERROR]:       at revxrsal.commands.velocity.core.VelocitySimpleCommand.execute(VelocitySimpleCommand.java:12)
[09:31:25 ERROR]:       at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81)
[09:31:25 ERROR]:       at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[09:31:25 ERROR]:       at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:230)
[09:31:25 ERROR]:       at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:279)
[09:31:25 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[09:31:25 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[09:31:25 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[09:31:25 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[09:31:29 ERROR]: java.lang.NullPointerException: message
[09:31:29 ERROR]:       at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
[09:31:29 ERROR]:       at com.velocitypowered.proxy.connection.client.ConnectedPlayer.sendMessage(ConnectedPlayer.java:393)
[09:31:29 ERROR]:       at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:253)
[09:31:29 ERROR]:       at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:217)
[09:31:29 ERROR]:       at revxrsal.commands.velocity.core.VelocityActor.reply(VelocityActor.java:62)
[09:31:29 ERROR]:       at com.bivashy.limbo.command.exception.SendComponentException.send(SendComponentException.java:19)
[09:31:29 ERROR]:       at com.bivashy.limbo.command.LampVelocityCommandHandler.lambda$registerAll$1(LampVelocityCommandHandler.java:32)
[09:31:29 ERROR]:       at revxrsal.commands.core.BaseCommandHandler$WrappedExceptionHandler.handleException(BaseCommandHandler.java:596)
[09:31:29 ERROR]:       at revxrsal.commands.core.BaseCommandDispatcher.eval(BaseCommandDispatcher.java:49)
[09:31:29 ERROR]:       at revxrsal.commands.core.BaseCommandHandler.dispatch(BaseCommandHandler.java:519)
[09:31:29 ERROR]:       at revxrsal.commands.velocity.core.VelocitySimpleCommand.execute(VelocitySimpleCommand.java:27)
[09:31:29 ERROR]:       at revxrsal.commands.velocity.core.VelocitySimpleCommand.execute(VelocitySimpleCommand.java:12)
[09:31:29 ERROR]:       at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81)
[09:31:29 ERROR]:       at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[09:31:29 ERROR]:       at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:230)
[09:31:29 ERROR]:       at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:279)
[09:31:29 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[09:31:29 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[09:31:29 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[09:31:29 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)


[09:29:13 ERROR]: java.lang.NullPointerException: message
[09:29:13 ERROR]:       at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
[09:29:13 ERROR]:       at com.velocitypowered.proxy.connection.client.ConnectedPlayer.sendMessage(ConnectedPlayer.java:393)
[09:29:13 ERROR]:       at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:253)
[09:29:13 ERROR]:       at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:217)
[09:29:13 ERROR]:       at revxrsal.commands.velocity.core.VelocityActor.reply(VelocityActor.java:62)
[09:29:13 ERROR]:       at com.bivashy.limbo.command.exception.VelocityExceptionHandler.missingArgument(VelocityExceptionHandler.java:20)
[09:29:13 ERROR]:       at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[09:29:13 ERROR]:       at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758)
[09:29:13 ERROR]:       at revxrsal.commands.core.reflect.MethodHandlesCallerFactory$1.call(MethodHandlesCallerFactory.java:35)
[09:29:13 ERROR]:       at revxrsal.commands.core.reflect.MethodCaller.lambda$bindTo$0(MethodCaller.java:29)
[09:29:13 ERROR]:       at revxrsal.commands.exception.CommandExceptionAdapter.lambda$register$0(CommandExceptionAdapter.java:160)
[09:29:13 ERROR]:       at revxrsal.commands.exception.CommandExceptionAdapter.handleException(CommandExceptionAdapter.java:130)
[09:29:13 ERROR]:       at revxrsal.commands.core.BaseCommandHandler$WrappedExceptionHandler.handleException(BaseCommandHandler.java:599)
[09:29:13 ERROR]:       at revxrsal.commands.core.BaseCommandDispatcher.eval(BaseCommandDispatcher.java:49)
[09:29:13 ERROR]:       at revxrsal.commands.core.BaseCommandHandler.dispatch(BaseCommandHandler.java:519)
[09:29:13 ERROR]:       at revxrsal.commands.velocity.core.VelocitySimpleCommand.execute(VelocitySimpleCommand.java:27)
[09:29:13 ERROR]:       at revxrsal.commands.velocity.core.VelocitySimpleCommand.execute(VelocitySimpleCommand.java:12)
[09:29:13 ERROR]:       at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81)
[09:29:13 ERROR]:       at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[09:29:13 ERROR]:       at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:230)
[09:29:13 ERROR]:       at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:279)
[09:29:13 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[09:29:13 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[09:29:13 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[09:29:13 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)```

Running on the latest version of velocity

**Comment by bivashy** [comment]
Configuration corrupted/Misses message `no-argument`.

https://github.com/bivashy/NanoLimboPlugin/blob/main/velocity%2Fsrc%2Fmain%2Fjava%2Fcom%2Fbivashy%2Flimbo%2Fcommand%2FConnectionCountCommand.java#L21
