### ISSUE TITLE
Dependency issue 

### ISSUE THREAD

**Issue by SpigotRCE** [bivashy/NanoLimboPlugin#14]
adding 

       <dependency>
            <groupId>com.github.bivashy.NanoLimboPlugin</groupId>
            <artifactId>api</artifactId>
            <version>1.0.6</version>
        </dependency>

        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>

causes  "Cannot access net. kyori. examination. Examinable"
![image](https://github.com/user-attachments/assets/75e6ec8e-7741-40d6-8c96-11b3c68ea888)

**Comment by bivashy** [comment]
Try to provide more info about your `pom.xml`, and try to use `1.0.11` instead of `1.0.6`

**Comment by SpigotRCE** [comment]
Nvm, it got fixed, I just added the kyori dependency in my pom. 

However I am getting an error when starting a limboserver

```
[17:32:10 ERROR] [core-velocity]: Failed to start Limbo Server
java.io.FileNotFoundException: Cannot find dimension registry file
        at ua.nanit.limbo.world.DimensionRegistry.readCodecFile(DimensionRegistry.java:160) ~[?:?]
        at ua.nanit.limbo.world.DimensionRegistry.load(DimensionRegistry.java:105) ~[?:?]
        at ua.nanit.limbo.server.LimboServer.start(LimboServer.java:93) ~[?:?]
        at org.nexuscraft.corevelocity.misc.LimboManager.createLimboServer(LimboManager.java:52) ~[?:?]
        at org.nexuscraft.corevelocity.misc.ServerHandler.onLimboRequest(ServerHandler.java:42) ~[?:?]
        at org.nexuscraft.corevelocity.listener.PlayerServerListener.onConnectionRequest(PlayerServerListener.java:38) ~[?:?]
        at org.nexuscraft.corevelocity.listener.Lmbda$32.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-dfe5f54f)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.3.0-SNAPSHOT (git-dfe5f54f)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.3.0-SNAPSHOT (git-dfe5f54f)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```
