### ISSUE TITLE
How do I use this plugin?

### ISSUE THREAD

**Issue by d0ddn** [bivashy/NanoLimboPlugin#18]
I want to use mc-auth so that it throws me into limbo and then lets me into the server through this plugin, I tried several options and none of them work for me

velocity.toml

[servers]
main = "localhost"
first = "localhost:65535" # NanoLimboPlugin

try = [
    "first"
] 

Error: 
```
Couldn't pass ProxyInitializeEvent to nanolimbovelocity 1.0.11
java.lang.IllegalArgumentException: Server with name first already registered
        at com.velocitypowered.proxy.server.ServerMap.register(ServerMap.java:87) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at com.velocitypowered.proxy.VelocityServer.registerServer(VelocityServer.java:710) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at com.bivashy.limbo.NanoLimboVelocity.onProxyInitialize(NanoLimboVelocity.java:54) ~[?:?]
        at com.bivashy.limbo.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

I also tried others, for example, connecting to main so that mc-auth itself would throw me to the main server, but it doesn’t want to work.

**Comment by d0ddn** [comment]
resolved: Use mc-auth 1.8.0 beta
